apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NaveedAmanat/KubeMwGatewayArtifact.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: devolpment

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true