apiVersion: apps/v1
kind: Deployment
metadata:
  name: kashf-gateway
  namespace: devolpment
spec:
  selector:
    matchLabels:
      app: kashf-gateway
  replicas: 3
  template:
    metadata:
      labels:
        app: kashf-gateway
    spec:
      containers:
      - name: kashf-gateway
        image:navedamanat/kashf-gateway:latest

        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kashf-gateway-service
  namespace: devolpment
spec:
  selector:
    app: kashf-gateway
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: devolpment
  name: kashf-devolpment-com
  labels:
    app: kashf-devolpment
spec:
  rules:
  - host: kashf.devolpment.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: kashf-gateway-service
            port:
              name: http
